In [1]:
import pandas as pd
from random import choices, randint, choice

from init import item_codes, warehouse_codes, number_of_transfers, start_date, internal_transfer_days

In [2]:
current_date = start_date
current_IT_number = 1
current_IT_item_number = 1
transfer_frequency = 0.95
combined_IT_frequency = 0.9

transfers = []
for i in range(number_of_transfers):
    
    # New date?
    if choices(population=[True,False],weights=[transfer_frequency, 1 - transfer_frequency])[0]:
        current_date = current_date + pd.DateOffset(days=randint(0,5))

    # Arrival date
    arrival_date = current_date + pd.DateOffset(days=randint(0, internal_transfer_days))
        
    # New IT?
    if choices(population=[True,False],weights=[combined_IT_frequency, 1 - combined_IT_frequency])[0]:
        current_IT_number += 1
        current_IT_item_number = 1
    zeros = "0"*(3-len(str(current_IT_number)))
    IT_number = 'IT' + zeros + str(current_IT_number)
    IT_item_number = IT_number + '-' + str(current_IT_item_number)
    current_IT_item_number += 1
    
    # Choose the 2 warehouses the goods are transferred between
    warehouse_from = choice(warehouse_codes)
    possible_destination = warehouse_codes.copy()
    possible_destination.remove(warehouse_from)
    warehouse_to = choice(possible_destination)
    
    #Select a random item to be transferred
    item_code = choice(item_codes)
    
    transfers.append([IT_item_number, IT_number, current_date, warehouse_from, arrival_date ,warehouse_to, item_code, randint(1, 50)*10])

df = pd.DataFrame(transfers, columns=['Element_Code', 'Element_Number', 'Date_Origin', 'Warehouse_Origin', 'Date_Arrival' ,'Warehouse_Destination', 'Item_Code', 'Amount'])
df

,Element_Code,Element_Number,Date_Origin,Warehouse_Origin,Date_Arrival,Warehouse_Destination,Item_Code,Amount
0,IT002-1,IT002,2025-01-02,WH001,2025-01-11,WH002,Item005,120
1,IT003-1,IT003,2025-01-02,WH002,2025-01-11,WH003,Item013,320
2,IT004-1,IT004,2025-01-03,WH001,2025-01-12,WH002,Item005,280
3,IT005-1,IT005,2025-01-04,WH001,2025-01-04,WH003,Item009,90
4,IT006-1,IT006,2025-01-05,WH001,2025-01-13,WH002,Item002,120
5,IT007-1,IT007,2025-01-09,WH001,2025-01-15,WH003,Item003,160
6,IT008-1,IT008,2025-01-13,WH002,2025-01-15,WH001,Item007,360
7,IT009-1,IT009,2025-01-13,WH002,2025-01-21,WH001,Item011,160
8,IT010-1,IT010,2025-01-17,WH001,2025-01-22,WH003,Item002,290
9,IT011-1,IT011,2025-01-19,WH003,2025-01-22,WH001,Item009,70
10,IT012-1,IT012,2025-01-24,WH001,2025-01-26,WH003,Item001,140
11,IT013-1,IT013,2025-01-24,WH002,2025-01-28,WH003,Item013,220
12,IT014-1,IT014,2025-01-26,WH001,2025-02-05,WH002,Item006,320
13,IT015-1,IT015,2025-01-26,WH001,2025-01-31,WH003,Item010,30
14,IT016-1,IT016,2025-01-28,WH003,2025-01-28,WH002,Item010,200
15,IT017-1,IT017,2025-01-28,WH002,2025-02-01,WH003,Item002,460
16,IT018-1,IT018,2025-02-02,WH001,2025-02-08,WH002,Item011,330
17,IT019-1,IT019,2025-02-03,WH003,2025-02-09,WH002,Item005,390
18,IT020-1,IT020,2025-02-06,WH003,2025-02-08,WH001,Item012,380
19,IT021-1,IT021,2025-02-11,WH003,2025-02-21,WH002,Item001,190

In [3]:
import os

# Ensure the target directory exists before saving the file
os.makedirs("../Datasets", exist_ok=True)

# Save DataFrame as CSV into existing directory
df.to_csv("../Datasets/Internal_Transfers.csv", index=False)