In [1]:
import pandas as pd
from datetime import date
from random import choices, randint, choice

from init import item_codes, warehouse_codes, start_date, number_of_outbounds

In [2]:
current_date = start_date
current_SO_number = 1
current_SO_item_number = 1
outbound_frequency = 0.3 # the higher this number, the less frequently goods is sold in a day
combined_SO_frequency = 0.9 # the lower this number, the more items are combined in a SO

outbounds = []
for i in range(number_of_outbounds):

    # New date?
    if choices(population=[True,False],weights=[outbound_frequency, 1 - outbound_frequency])[0]:
        current_date = current_date + pd.DateOffset(days=randint(1,3))

    # New SO?
    if choices(population=[True,False],weights=[combined_SO_frequency, 1 - combined_SO_frequency])[0]:
        current_SO_number += 1
        current_SO_item_number = 1
    zeros = "0"*(3-len(str(current_SO_number)))
    SO_number = 'SO' + zeros + str(current_SO_number)
    SO_item_number = SO_number + '-' + str(current_SO_item_number)
    current_SO_item_number += 1

    # Select a random Item sold outbound
    item_outbound = choice(item_codes)

    # Select a random Warehouse outbound from
    warehouse_outbound = choice(warehouse_codes)

    outbounds.append([SO_item_number,SO_number,current_date,warehouse_outbound,item_outbound,randint(1,100)*10])

df = pd.DataFrame(outbounds,columns=["Element_Code","Element_Number","Date","Warehouse_Code","Item_Code","Amount"])
df["Date"] = pd.to_datetime(df["Date"])
df

   Element_Code Element_Number       Date Warehouse_Code Item_Code  Amount
0       SO002-1          SO002 2025-01-03          WH002   Item001     490
1       SO003-1          SO003 2025-01-03          WH001   Item003     170
2       SO004-1          SO004 2025-01-04          WH001   Item013     160
3       SO005-1          SO005 2025-01-04          WH003   Item001     520
4       SO005-2          SO005 2025-01-04          WH002   Item001     870
..          ...            ...        ...            ...       ...     ...
95      SO084-1          SO084 2025-03-07          WH003   Item014     130
96      SO085-1          SO085 2025-03-07          WH001   Item004     810
97      SO085-2          SO085 2025-03-09          WH001   Item014      90
98      SO086-1          SO086 2025-03-12          WH003   Item012     670
99      SO087-1          SO087 2025-03-12          WH001   Item014     160

[100 rows x 6 columns]

In [3]:
import os

# Ensure the target directory exists before saving the file
os.makedirs("../Datasets", exist_ok=True)

# Save DataFrame as CSV into existing directory
df.to_csv("../Datasets/Outbound.csv", index=False)